# Generated by Django 5.0.3 on 2024-03-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gov', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gov',
            options={'verbose_name': 'Gov', 'verbose_name_plural': 'Gov'},
        ),
    ]
